FROM golang:1.20

# Set the working directory
WORKDIR /app

# Copy the necessary files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the application's source code
COPY . .

# Build the application
RUN go build -o hn .

# Start the application
CMD [ "./hn" ]
